// Auto-generated GIF mapping for exercises
// Source: Local public folder (/gifs)
// Generated by upload_to_local.js — DO NOT EDIT MANUALLY

export const gifMapping: Record<string, string> = {

// Cardio/HIIT
  "card1": "/gifs/card1.gif",
  "card2": "/gifs/card2.gif",
  "card3": "/gifs/card3.gif",
  "card4": "/gifs/card4.gif",
  "card5": "/gifs/card5.gif",
  "card6": "/gifs/card6.gif",
  "card7": "/gifs/card7.gif",
  "card8": "/gifs/card8.gif",
  "card9": "/gifs/card9.gif",
  "card10": "/gifs/card10.gif",
  "card11": "/gifs/card11.gif",

// Core
  "core1": "/gifs/core1.gif",
  "core2": "/gifs/core2.gif",
  "core3": "/gifs/core3.gif",
  "core4": "/gifs/core4.gif",
  "core5": "/gifs/core5.gif",
  "core6": "/gifs/core6.gif",
  "core7": "/gifs/core7.gif",
  "core8": "/gifs/core8.gif",
  "core9": "/gifs/core9.gif",
  "core10": "/gifs/core10.gif",
  "core11": "/gifs/core11.gif",

// Lower Body
  "lb1": "/gifs/lb1.gif",
  "lb2": "/gifs/lb2.gif",
  "lb3": "/gifs/lb3.gif",
  "lb4": "/gifs/lb4.gif",
  "lb5": "/gifs/lb5.gif",
  "lb6": "/gifs/lb6.gif",
  "lb7": "/gifs/lb7.gif",
  "lb8": "/gifs/lb8.gif",
  "lb9": "/gifs/lb9.gif",
  "lb10": "/gifs/lb10.gif",
  "lb11": "/gifs/lb11.gif",

// Plyometric
  "ply1": "/gifs/ply1.gif",
  "ply2": "/gifs/ply2.gif",
  "ply3": "/gifs/ply3.gif",
  "ply4": "/gifs/ply4.gif",
  "ply5": "/gifs/ply5.gif",
  "ply6": "/gifs/ply6.gif",
  "ply7": "/gifs/ply7.gif",
  "ply8": "/gifs/ply8.gif",
  "ply9": "/gifs/ply9.gif",
  "ply10": "/gifs/ply10.gif",
  "ply11": "/gifs/ply11.gif",

// Upper Push
  "up1": "/gifs/up1.gif",
  "up2": "/gifs/up2.gif",
  "up3": "/gifs/up3.gif",
  "up4": "/gifs/up4.gif",
  "up5": "/gifs/up5.gif",
  "up6": "/gifs/up6.gif",
  "up7": "/gifs/up7.gif",
  "up8": "/gifs/up8.gif",
  "up9": "/gifs/up9.gif",
  "up10": "/gifs/up10.gif",
  "up11": "/gifs/up11.gif",

// Upper Pull
  "upl1": "/gifs/upl1.gif",
  "upl2": "/gifs/upl2.gif",
  "upl3": "/gifs/upl3.gif",
  "upl4": "/gifs/upl4.gif",
  "upl5": "/gifs/upl5.gif",
  "upl6": "/gifs/upl6.gif",
  "upl7": "/gifs/upl7.gif",
  "upl8": "/gifs/upl8.gif",
  "upl9": "/gifs/upl9.gif",
  "upl10": "/gifs/upl10.gif",
  "upl11": "/gifs/upl11.gif",
};

/**
 * Get GIF URL for an exercise ID.
 * Returns null if no GIF is mapped.
 */
export function getGifUrl(exerciseId: string): string | null {
  return gifMapping[exerciseId] ?? null;
}

/**
 * Get all exercise IDs that have GIFs mapped.
 */
export function getMappedExerciseIds(): string[] {
  return Object.keys(gifMapping);
}
